"""add date

Revision ID: 53393955a9fc
Revises: 5debd8535f1e
Create Date: 2021-03-03 15:18:59.729118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53393955a9fc'
down_revision = '5debd8535f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deadline', sa.Date(), nullable=True))
    op.create_index(op.f('ix_todos_deadline'), 'todos', ['deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_deadline'), table_name='todos')
    op.drop_column('todos', 'deadline')
    # ### end Alembic commands ###
